### ISSUE TITLE
vmmlib lacks of find_package 

### ISSUE THREAD

**Issue by adevress** [Eyescale/vmmlib#43]
Vmmlib is the only component in the BBP/viz stack that does not install a cmake Target file by default.

Due to this it cannot be discovered automatically through common_package and is downloaded systematically, even if already installed or present inside the CMAKE_PREFIX_PATH

As vmmlib is an header only library and the target generation for header only library is buggy under cmake 2.8, would it be possible to include directly a find_package module file for vmmlib in CMake / Common ?

Adev

**Comment by eile** [comment]
Can't reproduce:
    [tsf-484-wpa-2-061 Livre sortlast]% clear ; ninja -C ../build install
    [...]
    [tsf-484-wpa-2-061 Livre sortlast]% ls ../build/install/share/vmmlib/CMake/
options.cmake			vmmlibConfig.cmake		vmmlibConfigVersion.cmake	vmmlibTargets.cmake

**Comment by eile** [comment]
You do need cmake 3 for this. We will make this mandatory as soon as Ubuntu 16.04 is out, so better get ready.

**Comment by adevress** [comment]
That's fine for me, as long as it is consistent and we have cmake 3 everywhere, which should be the case.
